apiVersion: batch/v1
kind: Job
metadata:
  name: golang-job
spec:
  completions: 4
  parallelism: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: golang-job
          image: golang
          ports:
            - containerPort: 8080

